### ISSUE TITLE
Don't have 23 <-> 24 option in the menu audio conversion

### ISSUE THREAD

**Issue by kedaitinh12** [Kurtnoise-zeus/megui#1]
I don't have this option in the menu audio conversion
![image](https://github.com/Kurtnoise-zeus/megui/assets/66716952/7c401534-d637-44c8-b9bb-8385a2c69a79)

**Comment by Kurtnoise-zeus** [comment]
You're right. Forgot to add it through the UI. Will do.

**Comment by Kurtnoise-zeus** [comment]
Fixed through commit #db50970

**Comment by johnloopi** [comment]
Hi, @Kurtnoise-zeus, I see you've added both ""SlowDown24To23976WithCorrection" and "SpeedUp23976To24WithCorrection" and I'm wondering if it would be possible to also add the regular "SlowDown24To23976" and "SpeedUp23976To24" without the pitch correction?

**Comment by Kurtnoise-zeus** [comment]
Hi @johnloopi . It has just been added.

**Comment by johnloopi** [comment]
> Hi @johnloopi . It has just been added.

Thank you very much. 😄
