### ISSUE TITLE
6666.2308 bug update 

### ISSUE THREAD

**Issue by forapreder** [Kurtnoise-zeus/megui#11]
6666.2308 x64 requires updating components to older versions.
![Без-имени-1](https://github.com/user-attachments/assets/1dc7fa43-1a65-487a-a32d-587bb2a0c70e)

**Comment by Kurtnoise-zeus** [comment]
I recommend to install this new release into a new folder and update components afterwards.

I get this on my side using development server :
![Sans titre](https://github.com/user-attachments/assets/7b951b38-8d32-4d7c-b4dc-d0937fc06167)

**Comment by forapreder** [comment]
Thank you very much. Everything worked out. There is no more error.
