### ISSUE TITLE
MeGui closed suddenly 

### ISSUE THREAD

**Issue by reeunnn** [Kurtnoise-zeus/megui#12]
I am using MeGUI version 6666.2308
When trying to use AutoEncode and selecting NoTargetSize (use profile settings), MeGUI suddenly exits by itself without any notification.

I am attaching the log file.
[logfile-24-08-24_07-19-19.log](https://github.com/user-attachments/files/16755287/logfile-24-08-24_07-19-19.log)

**Comment by Kurtnoise-zeus** [comment]
It seems your AvisynthWrapper.dll is missing or too old. How did you get this package ?

**Comment by Kurtnoise-zeus** [comment]
Any chance to have the whole logfile ? you should have it in the log subfolder...

Did you try with another input file ?

**Comment by reeunnn** [comment]
> Any chance to have the whole logfile ? you should have it in the log subfolder...
> I dont have anymore the rest logfile, cause i re-install my windows.

> Did you try with another input file ?
> I just try File Indexer and didnt work with MKV file or MP4. 

Now revert back to using MeGUI 2913.

**Comment by reeunnn** [comment]
I dont have anymore the rest logfile, cause i re-install my windows.

 I just try File Indexer and didnt work with MKV file or MP4. 

Now revert back to using MeGUI 2913.

**Comment by Kurtnoise-zeus** [comment]
I cant help you without so few log informations unfortunately.

**Comment by reeunnn** [comment]
> I cant help you without so few log informations unfortunately.

I found the problem, i dont know if a "bug" or not.
but in audio encoding config, i change Preferred Decoder to DirectShow and it works perfect, when using LWLibavAudioSource, MeGUI Suddenly closed.

Note:
I try other Preferred Decoder (NicAudio, FFAudio) and its works, but not when using LWLibav.

![image](https://github.com/user-attachments/assets/9259d10e-16bd-444c-a14d-acc6a6a7b395)
