### ISSUE TITLE
Why only x64 version?

### ISSUE THREAD

**Issue by obiwan-bartek** [Kurtnoise-zeus/megui#3]
Hi,

Is there any particular reason for only x64 build? I can try to help with x86 release and testing (I use it regularly).

**Comment by Kurtnoise-zeus** [comment]
Hi,

Here you go : https://github.com/Kurtnoise-zeus/megui/releases/download/6666.0204/MeGUI.x86-6666.0304.zip

Not tested though.

**Comment by Barough** [comment]
Great to see an x86 build now also. Saves me a lot of time re-making my profiles

**Comment by Kurtnoise-zeus** [comment]
> The only thing i've noticed with the x86 is that downloading/updating (dev server) x265 encoder is just going in a loop

Im not able to reproduce this issue here...Did you retry later ?

**Comment by Barough** [comment]
> > The only thing i've noticed with the x86 is that downloading/updating (dev server) x265 encoder is just going in a loop
> 
> Im not able to reproduce this issue here...Did you retry later ?

I just deleted the contents of the x265 folder and after that so did it update just fine

**Comment by Kurtnoise-zeus** [comment]
Closed this ticket. 32 bits assets are also provided but not tested nor maintained.
