### ISSUE TITLE
File Indexer

### ISSUE THREAD

**Issue by AlreadyFree** [Kurtnoise-zeus/megui#4]
First thank you in general for continuing development on this in zathor's absence. And also thank you for implementing my suggestion about the standardized output file naming.

I've been playing around with your 6666.204 version the last 3 days using Windows 10 and had an initial problem with it not wanting to load any of my saved avisynth profiles and dumping them all into the backup folder. I figured out there's a few differences in terminology that I have to manually change in the files to make them work so it's just a minor inconvenience.

However the other issue I noticed is whenever loading a file with the file indexer it wants to start the indexer twice. As in I go to the file tab, open, select file, click file indexer on choose your preferred tool menu and then it opens the file indexer selection menu as usual but also immediately opens the preferred tool menu again and clicking on any selection causes an error: 

MeGUI encounted a fatal error and may not be able to proceed. Reason: Cannot access a disposed object. Object name: 'AvisynthWindow'.

I'm assuming that the error is cause by trying to open 2 instances of the file indexer. Closing the error and using the first file indexer menu works normally.

**Comment by Kurtnoise-zeus** [comment]
Hi,

What kind of input file you're trying to index ?

**Comment by Kurtnoise-zeus** [comment]
strange...which indexer did you choose ? could you please post a logfile ?

**Comment by AlreadyFree** [comment]
I get the same result choosing One Click Encoder or File Indexer.

Looking at the log I'd suspect that these lines have at least something to do with the problem since they don't reference any path on my system, either past or present:

-[NoImage]    at MeGUI.MainForm.openFile(String file) in C:\Users\LionelDUCHATEAU\Downloads\megui_git\megui\core\gui\MainForm.cs:line 715
-[NoImage]    at MeGUI.MainForm.mnuFileOpen_Click(Object sender, EventArgs e) in C:\Users\LionelDUCHATEAU\Downloads\megui_git\megui\core\gui\MainForm.cs:line 554

[logfile-24-04-16_10-32-36.log](https://github.com/Kurtnoise-zeus/megui/files/14998509/logfile-24-04-16_10-32-36.log)

**Comment by Kurtnoise-zeus** [comment]
Issue fixed in #[d4ddc2e](https://github.com/Kurtnoise-zeus/megui/commit/d4ddc2e9633e734d789f7913d6b2fb2a405b3710)
