### ISSUE TITLE
megui 6666 32 or 64 mp4box mux x264 error, 2944-32 stable is ok,  mp4box is the same version

### ISSUE THREAD

**Issue by longwu9t** [Kurtnoise-zeus/megui#5]
[Error] Log for job3 (mux, cat.mkv_hbwoiadq.mkv -> cat.mkv-muxed.mp4)
-[Information] [2024/5/6 12:49:32] Started handling job
-[Information] [2024/5/6 12:49:32] Preprocessing
-[Information] [2024/5/6 12:49:32] MediaInfo
--[Information] File: D:\vdo\cat.mkv_hbwoiadq.mkv
--[Information] General
---[Information] Format: Matroska
---[Information] FileSize: 1234133
---[Information] PlayTime: 00:00:08.367
--[Information] Video
---[Information] ID: 1
---[Information] StreamOrder: 0
---[Information] CodecID: V_MPEG4/ISO/AVC
---[Information] Format: AVC
---[Information] FormatInfo: Advanced Video Codec
---[Information] Width: 720
---[Information] Height: 1280
---[Information] FrameCount: 251
---[Information] FrameRate: 30.000
---[Information] FrameRate_N: 30
---[Information] FrameRate_D: 1
---[Information] FrameRateMode: CFR
---[Information] FrameRateModeString: Constant
---[Information] Duration: 00:00:08.367
---[Information] ScanType: Progressive
---[Information] Bits Depth: 8
---[Information] AspectRatio: 0.562
---[Information] AspectRatioString: 0.562
---[Information] PixelAspectRatio: 1.000
---[Information] Delay: 0
---[Information] LanguageString: English
---[Information] Default: Yes
---[Information] Forced: No
-[Information] [2024/5/6 12:49:32] MediaInfo
--[Information] File: D:\vdo\cat - [0] English_scbxhjta.ac3
--[Information] General
---[Information] Format: AC-3
---[Information] FileSize: 402912
---[Information] PlayTime: 00:00:08.394
--[Information] Audio
---[Information] Format: AC-3
---[Information] FormatInfo: Audio Coding 3
---[Information] FormatCommercial: Dolby Digital
---[Information] SamplingRate: 44100
---[Information] SamplingRateString: 44.1 kHz
---[Information] Channels: 2
---[Information] ChannelsString: 2 channels
---[Information] ChannelLayout: L R
---[Information] BitRateMode: CBR
---[Information] [2024/5/6 12:49:32] The language information is not available for this track. The default MeGUI language has been selected.
-[Information] [2024/5/6 12:49:32] Job command line: "C:\MeGUI\tools\mp4box\mp4box.exe" -add "D:\vdo\cat.mkv_hbwoiadq.mkv#trackID=1:fps=30/1:par=1:1:name=" -add "D:\vdo\cat - [0] English_scbxhjta.ac3#trackID=1:lang=eng:name=" -tmp "C:\\temp" -new "D:\vdo\cat.mkv-muxed.mp4"
-[Information] [2024/5/6 12:49:32] Process started
-[Information] [2024/5/6 12:49:32] Standard output stream
-[Information] [2024/5/6 12:49:32] Standard error stream
--[Information] [2024/5/6 12:49:32] Filter fin failed to setup: Filter not found for the desired type
--[Information] [2024/5/6 12:49:32] [Importer] Error probing D:\vdo\cat.mkv_hbwoiadq.mkv
--[Information] [2024/5/6 12:49:32] Failure while importing import: Filter not found for the desired type
--[Information] [2024/5/6 12:49:32] Error importing D:\vdo\cat.mkv_hbwoiadq.mkv#trackID=1:fps=30/1:par=1:1:name=: Filter not found for the desired type
-[Error] [2024/5/6 12:49:32] Process exits with error: 1
-[Information] [2024/5/6 12:49:32] Job completed

**Comment by Kurtnoise-zeus** [comment]
Thanks. Fixed.
