### ISSUE TITLE
MeGUI 6666.1007 (x86 & x64) / Missing component / AviSynth plugins 13

### ISSUE THREAD

**Issue by Barough** [Kurtnoise-zeus/megui#7]
After updating to MeGUI 6666.1007 (x86 & x64) so does MeGUI report that a component is missing. It needs to reinstall AviSynth plugins 13, but it keeps asking the same thing every time you start MeGUI after the reinstallation of the plugins..

**Comment by Kurtnoise-zeus** [comment]
Strange because this package has not been updated...did you update manually ?

**Comment by forapreder** [comment]
I have the same error.
6666.1007 x64. Constantly requires updating AviSynth plugins. MeGUI complete Local Version bild 13, Server Version 13. After reinstall it MeGUI requires updating again and again.
6666.1405 x64 all right.

**Comment by Kurtnoise-zeus** [comment]
Fixed. Sorry.

You can redownload [the latest release](https://github.com/Kurtnoise-zeus/megui/releases/tag/6666.1007). Its updated from now.

**Comment by Barough** [comment]
Both x86 & x64 work as they should now. Thanks :)
