### ISSUE TITLE
the profiles could not be saved

### ISSUE THREAD

**Issue by foremtehan** [Kurtnoise-zeus/megui#9]
![image](https://github.com/user-attachments/assets/10fb1dd5-551e-4a41-a6f8-58d12ee6d410)

I'm in the situation where megui doesn't let me to save profiles anymore

![image](https://github.com/user-attachments/assets/91fd9d93-04e5-4210-b07e-3f163d3e143e)

**Comment by Kurtnoise-zeus** [comment]
Sorry, I'm not maintaining MeGUI 2944 x64...please use [latest release](https://github.com/Kurtnoise-zeus/megui/releases) from my fork.
